steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/superaps_boo', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/superaps_boo']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'superaps_boo',
         '--image', 'gcr.io/$PROJECT_ID/superaps_boo',
         '--region', 'asia-southeast1',
         '--platform', 'managed',
         '--allow-unauthenticated']

images:
- 'gcr.io/$PROJECT_ID/superaps_boo'
